syntax on
colorscheme koehler
filetype on
set autoindent
"set colorcolumn=80
set expandtab smarttab
set hlsearch
set ignorecase
set incsearch
set laststatus=2
"set mouse=a
set number
set ruler
set showmatch
set smartcase
set smartindent
set shiftwidth=4
set softtabstop=4
set tabstop=4
set undolevels=500
