syntax on
color wombat  "https://raw.githubusercontent.com/gryf/wombat256grf/master/colors/wombat256grf.vim
set nocindent
set tabstop=4
set smartindent
set ai
set ruler
set hlsearch
set number
set et
set sts=4
set ts=4
set expandtab
set undolevels=500
set showmatch
set incsearch
set ignorecase
set smartcase
filetype on
